version: 1

checks:
  - name: "format"
    run: "mix format --check-formatted"
  - name: "tests"
    run: "mix test"

insults:
  mode: "snarky"
  file: ".buildbouncer/assets/insults/default.json"
  locale: "en"

banter:
  enabled: true
  file: ".buildbouncer/assets/banter/default.json"
  locale: "en"

