version: 1

checks:
  - name: "tests"
    run: "prove -lr t"

insults:
  mode: "snarky"
  file: ".buildbouncer/assets/insults/default.json"
  locale: "en"

banter:
  file: ".buildbouncer/assets/banter/default.json"
  locale: "en"

